/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package frames;

import javax.swing.JOptionPane;

/**
 *
 * @author ID145
 */
public class agregarVentaForm extends javax.swing.JFrame {

    /**
     * Creates new form agregarVentaForm
     */
    public agregarVentaForm() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel4 = new javax.swing.JLabel();
        botonSalir = new javax.swing.JButton();
        botonCompletar = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        fieldNombreCliente = new javax.swing.JTextField();
        fieldApellidoCliente = new javax.swing.JTextField();
        metodoPagoComboBox = new javax.swing.JComboBox<>();
        fieldTotal = new javax.swing.JTextField();
        fieldPagoCon = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        tablaProductos = new javax.swing.JTable();
        jScrollPane2 = new javax.swing.JScrollPane();
        tablaProductosEnVenta = new javax.swing.JTable();
        jLabel8 = new javax.swing.JLabel();
        botonAgregarProductoAVenta = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(null);

        jPanel1.setBackground(new java.awt.Color(255, 153, 0));

        jLabel4.setFont(new java.awt.Font("Segoe UI", 1, 36)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(0, 0, 0));
        jLabel4.setText("Agregar Venta");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(227, Short.MAX_VALUE)
                .addComponent(jLabel4)
                .addGap(220, 220, 220))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel4)
                .addContainerGap(16, Short.MAX_VALUE))
        );

        getContentPane().add(jPanel1);
        jPanel1.setBounds(0, 0, 690, 70);

        botonSalir.setText("Salir");
        botonSalir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonSalirActionPerformed(evt);
            }
        });
        getContentPane().add(botonSalir);
        botonSalir.setBounds(130, 560, 100, 23);

        botonCompletar.setText("Completar Venta");
        botonCompletar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonCompletarActionPerformed(evt);
            }
        });
        getContentPane().add(botonCompletar);
        botonCompletar.setBounds(410, 560, 130, 23);

        jLabel2.setFont(new java.awt.Font("Segoe UI", 0, 16)); // NOI18N
        jLabel2.setText("Nombre cliente:");
        getContentPane().add(jLabel2);
        jLabel2.setBounds(20, 110, 110, 22);

        jLabel3.setFont(new java.awt.Font("Segoe UI", 0, 16)); // NOI18N
        jLabel3.setText("Apellido cliente:");
        getContentPane().add(jLabel3);
        jLabel3.setBounds(20, 160, 110, 22);

        jLabel5.setFont(new java.awt.Font("Segoe UI", 0, 16)); // NOI18N
        jLabel5.setText("Método de pago:");
        getContentPane().add(jLabel5);
        jLabel5.setBounds(10, 230, 120, 22);

        jLabel6.setFont(new java.awt.Font("Segoe UI", 0, 16)); // NOI18N
        jLabel6.setText("Total a pagar:");
        getContentPane().add(jLabel6);
        jLabel6.setBounds(20, 290, 100, 22);

        jLabel7.setFont(new java.awt.Font("Segoe UI", 0, 16)); // NOI18N
        jLabel7.setText("Pago con:");
        getContentPane().add(jLabel7);
        jLabel7.setBounds(370, 290, 70, 22);

        fieldNombreCliente.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        getContentPane().add(fieldNombreCliente);
        fieldNombreCliente.setBounds(140, 110, 360, 26);

        fieldApellidoCliente.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        getContentPane().add(fieldApellidoCliente);
        fieldApellidoCliente.setBounds(140, 170, 360, 22);

        metodoPagoComboBox.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "EFECTIVO", "TARJETA" }));
        metodoPagoComboBox.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                metodoPagoComboBoxActionPerformed(evt);
            }
        });
        getContentPane().add(metodoPagoComboBox);
        metodoPagoComboBox.setBounds(140, 230, 100, 22);

        fieldTotal.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                fieldTotalActionPerformed(evt);
            }
        });
        getContentPane().add(fieldTotal);
        fieldTotal.setBounds(140, 290, 100, 22);
        getContentPane().add(fieldPagoCon);
        fieldPagoCon.setBounds(470, 290, 90, 22);

        tablaProductos.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Nombre", "Codigo Interno", "Precio", "Fecha Registro"
            }
        ));
        jScrollPane1.setViewportView(tablaProductos);

        getContentPane().add(jScrollPane1);
        jScrollPane1.setBounds(10, 370, 410, 130);

        tablaProductosEnVenta.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {"SAB001",  new Float(500.0)},
                {null, null},
                {null, null},
                {null, null},
                {null, null}
            },
            new String [] {
                "Nombre", "Precio"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.Float.class
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }
        });
        jScrollPane2.setViewportView(tablaProductosEnVenta);

        getContentPane().add(jScrollPane2);
        jScrollPane2.setBounds(510, 370, 140, 130);

        jLabel8.setText("Productos en la Venta");
        getContentPane().add(jLabel8);
        jLabel8.setBounds(520, 350, 120, 16);

        botonAgregarProductoAVenta.setText("Agregar");
        getContentPane().add(botonAgregarProductoAVenta);
        botonAgregarProductoAVenta.setBounds(430, 400, 72, 23);

        setBounds(0, 0, 707, 655);
    }// </editor-fold>//GEN-END:initComponents

    private void metodoPagoComboBoxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_metodoPagoComboBoxActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_metodoPagoComboBoxActionPerformed

    private void botonCompletarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonCompletarActionPerformed
        String nombreCliente = fieldNombreCliente.getText().trim();
        String apellidoCliente = fieldApellidoCliente.getText().trim();
        String pagoConStr = fieldPagoCon.getText().trim();
        String totalStr = fieldTotal.getText().trim();

        // Validar que los campos no estén vacíos
        if (nombreCliente.isEmpty() || apellidoCliente.isEmpty() || pagoConStr.isEmpty()) {
            JOptionPane.showMessageDialog(agregarVentaForm.this, "Todos los campos deben estar llenos.", "Error", JOptionPane.ERROR_MESSAGE);
            return;
        }
        if (tablaProductosEnVenta.getRowCount() == 0) {
            JOptionPane.showMessageDialog(agregarVentaForm.this, "La tabla de productos a vender no puede estar vacía.", "Error", JOptionPane.ERROR_MESSAGE);
            return;
        }

        // Validar nombre del cliente
        if (!nombreCliente.matches("^[a-zA-Z]+$")) {
            JOptionPane.showMessageDialog(agregarVentaForm.this, "Nombre del Cliente solo puede contener letras.", "Error", JOptionPane.ERROR_MESSAGE);
            return;
        }

        // Validar apellido del cliente
        if (!apellidoCliente.matches("^[a-zA-Z]+$")) {
            JOptionPane.showMessageDialog(agregarVentaForm.this, "Apellido del Cliente solo puede contener letras.", "Error", JOptionPane.ERROR_MESSAGE);
            return;
        }

        // Validar total y pago con
        double total;
        double pagoCon;
        
        try {
            total = Double.parseDouble(totalStr);
        } catch (NumberFormatException ex) {
            JOptionPane.showMessageDialog(agregarVentaForm.this, "Total debe ser un número válido.", "Error", JOptionPane.ERROR_MESSAGE);
            return;
        }
        
        try {
            pagoCon = Double.parseDouble(pagoConStr);
        } catch (NumberFormatException ex) {
            JOptionPane.showMessageDialog(agregarVentaForm.this, "Pago Con debe ser un número válido.", "Error", JOptionPane.ERROR_MESSAGE);
            return;
        }
        
        if (pagoCon < total) {
            JOptionPane.showMessageDialog(agregarVentaForm.this, "Pago Con debe ser mayor o igual al Total.", "Error", JOptionPane.ERROR_MESSAGE);
            return;
        }
        
        if (pagoCon < 0) {
            JOptionPane.showMessageDialog(agregarVentaForm.this, "Pago Con no puede ser negativo.", "Error", JOptionPane.ERROR_MESSAGE);
            return;
        }


        // Si todas las validaciones son exitosas, proceder con la lógica de completar la venta
        JOptionPane.showMessageDialog(agregarVentaForm.this, "Venta completada exitosamente.");
    }//GEN-LAST:event_botonCompletarActionPerformed

    private void botonSalirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonSalirActionPerformed
        dispose();        // TODO add your handling code here:
    }//GEN-LAST:event_botonSalirActionPerformed

    private void fieldTotalActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_fieldTotalActionPerformed
        fieldTotal.setEditable(false);
    }//GEN-LAST:event_fieldTotalActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(agregarVentaForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(agregarVentaForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(agregarVentaForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(agregarVentaForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new agregarVentaForm().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton botonAgregarProductoAVenta;
    private javax.swing.JButton botonCompletar;
    private javax.swing.JButton botonSalir;
    private javax.swing.JTextField fieldApellidoCliente;
    private javax.swing.JTextField fieldNombreCliente;
    private javax.swing.JTextField fieldPagoCon;
    private javax.swing.JTextField fieldTotal;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JComboBox<String> metodoPagoComboBox;
    private javax.swing.JTable tablaProductos;
    private javax.swing.JTable tablaProductosEnVenta;
    // End of variables declaration//GEN-END:variables
}
