package frames;

import dtos.DireccionDTO;
import dtos.UsuarioDTO;
import excepciones.PersistenciaException;
import frames.logFrame;
import gestores.GestorUsuarios;
import pojos.Usuario;

import java.text.SimpleDateFormat;
import java.util.Date;
import java.util.logging.Level;
import java.util.logging.Logger;

import javax.swing.JOptionPane;

/**
 * Clase que representa la ventana de agregar usuario.
 * @author Fran
 */
public class agregarUsuarioFrame extends javax.swing.JFrame {

    /**
     * Creates new form agregarUsuarioFrame
     */
    public agregarUsuarioFrame() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel4 = new javax.swing.JLabel();
        botonCancelar = new javax.swing.JButton();
        botonAgregar = new javax.swing.JButton();
        botonRestablecer = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        fieldNombreUsuario = new javax.swing.JTextField();
        fieldApellidoUsuario = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        cajeroComboBox = new javax.swing.JComboBox<>();
        fieldTelefono = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        fieldCalle = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        fieldColonia = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        fieldCodigoPostal = new javax.swing.JTextField();
        jLabel9 = new javax.swing.JLabel();
        fieldCiudad = new javax.swing.JTextField();
        jLabel10 = new javax.swing.JLabel();
        fieldNumeroEdificio = new javax.swing.JTextField();
        jLabel11 = new javax.swing.JLabel();
        contrasenaField = new javax.swing.JPasswordField();
        checkboxConfirmarMostrarContrasena = new javax.swing.JCheckBox();
        checkboxMostrarContrasena = new javax.swing.JCheckBox();
        jLabel12 = new javax.swing.JLabel();
        confirmarContrasenaField = new javax.swing.JPasswordField();
        jLabel13 = new javax.swing.JLabel();
        fieldCodigoInterno = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(null);

        jPanel1.setBackground(new java.awt.Color(255, 153, 0));

        jLabel4.setFont(new java.awt.Font("Segoe UI", 1, 36)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(0, 0, 0));
        jLabel4.setText("Agregar Usuario");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(283, Short.MAX_VALUE)
                .addComponent(jLabel4)
                .addGap(293, 293, 293))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel4)
                .addContainerGap(16, Short.MAX_VALUE))
        );

        getContentPane().add(jPanel1);
        jPanel1.setBounds(0, 0, 850, 70);

        botonCancelar.setText("Salir");
        botonCancelar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonCancelarActionPerformed(evt);
            }
        });
        getContentPane().add(botonCancelar);
        botonCancelar.setBounds(70, 530, 90, 23);

        botonAgregar.setText("Agregar Usuario");
        botonAgregar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonAgregarActionPerformed(evt);
            }
        });
        getContentPane().add(botonAgregar);
        botonAgregar.setBounds(650, 530, 120, 23);

        botonRestablecer.setText("Restablecer");
        botonRestablecer.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonRestablecerActionPerformed(evt);
            }
        });
        getContentPane().add(botonRestablecer);
        botonRestablecer.setBounds(360, 530, 130, 23);

        jLabel1.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel1.setText("Nombre:");
        getContentPane().add(jLabel1);
        jLabel1.setBounds(20, 100, 60, 20);

        fieldNombreUsuario.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                fieldNombreUsuarioActionPerformed(evt);
            }
        });
        getContentPane().add(fieldNombreUsuario);
        fieldNombreUsuario.setBounds(80, 100, 230, 22);
        getContentPane().add(fieldApellidoUsuario);
        fieldApellidoUsuario.setBounds(440, 100, 230, 22);

        jLabel2.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel2.setText("Apellido:");
        getContentPane().add(jLabel2);
        jLabel2.setBounds(370, 100, 60, 20);

        jLabel3.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel3.setText("Puesto:");
        getContentPane().add(jLabel3);
        jLabel3.setBounds(20, 170, 60, 20);

        cajeroComboBox.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "CAJERO", "GERENTE" }));
        getContentPane().add(cajeroComboBox);
        cajeroComboBox.setBounds(80, 170, 110, 22);
        getContentPane().add(fieldTelefono);
        fieldTelefono.setBounds(440, 170, 230, 22);

        jLabel5.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel5.setText("Teléfono:");
        getContentPane().add(jLabel5);
        jLabel5.setBounds(370, 170, 60, 20);
        getContentPane().add(fieldCalle);
        fieldCalle.setBounds(80, 240, 130, 22);

        jLabel6.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel6.setText("Calle:");
        getContentPane().add(jLabel6);
        jLabel6.setBounds(20, 240, 60, 20);

        jLabel7.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel7.setText("Colonia:");
        getContentPane().add(jLabel7);
        jLabel7.setBounds(280, 240, 60, 20);
        getContentPane().add(fieldColonia);
        fieldColonia.setBounds(340, 240, 130, 22);

        jLabel8.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel8.setText("Código Postal:");
        getContentPane().add(jLabel8);
        jLabel8.setBounds(540, 240, 90, 20);
        getContentPane().add(fieldCodigoPostal);
        fieldCodigoPostal.setBounds(640, 240, 100, 22);

        jLabel9.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel9.setText("Ciudad:");
        getContentPane().add(jLabel9);
        jLabel9.setBounds(20, 310, 60, 20);
        getContentPane().add(fieldCiudad);
        fieldCiudad.setBounds(80, 310, 130, 22);

        jLabel10.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel10.setText("Número Edificio:");
        getContentPane().add(jLabel10);
        jLabel10.setBounds(280, 310, 100, 20);
        getContentPane().add(fieldNumeroEdificio);
        fieldNumeroEdificio.setBounds(390, 310, 130, 22);

        jLabel11.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel11.setText("Contraseña:");
        getContentPane().add(jLabel11);
        jLabel11.setBounds(90, 380, 73, 20);

        contrasenaField.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        contrasenaField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                contrasenaFieldActionPerformed(evt);
            }
        });
        getContentPane().add(contrasenaField);
        contrasenaField.setBounds(170, 380, 160, 26);

        checkboxConfirmarMostrarContrasena.setText("Mostrar Contraseña");
        checkboxConfirmarMostrarContrasena.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                checkboxConfirmarMostrarContrasenaActionPerformed(evt);
            }
        });
        getContentPane().add(checkboxConfirmarMostrarContrasena);
        checkboxConfirmarMostrarContrasena.setBounds(350, 430, 160, 20);

        checkboxMostrarContrasena.setText("Mostrar Contraseña");
        checkboxMostrarContrasena.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                checkboxMostrarContrasenaActionPerformed(evt);
            }
        });
        getContentPane().add(checkboxMostrarContrasena);
        checkboxMostrarContrasena.setBounds(350, 380, 170, 20);

        jLabel12.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel12.setText("Confirmar Contrasena:");
        getContentPane().add(jLabel12);
        jLabel12.setBounds(20, 430, 140, 20);

        confirmarContrasenaField.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        confirmarContrasenaField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                confirmarContrasenaFieldActionPerformed(evt);
            }
        });
        getContentPane().add(confirmarContrasenaField);
        confirmarContrasenaField.setBounds(170, 430, 160, 26);

        jLabel13.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel13.setText("Codigo Interno:");
        getContentPane().add(jLabel13);
        jLabel13.setBounds(540, 310, 100, 20);
        getContentPane().add(fieldCodigoInterno);
        fieldCodigoInterno.setBounds(650, 310, 130, 20);

        setBounds(0, 0, 863, 619);
    }// </editor-fold>//GEN-END:initComponents

    private void contrasenaFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_contrasenaFieldActionPerformed

    }//GEN-LAST:event_contrasenaFieldActionPerformed

    private void checkboxConfirmarMostrarContrasenaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_checkboxConfirmarMostrarContrasenaActionPerformed
        if (checkboxConfirmarMostrarContrasena.isSelected()) {
            confirmarContrasenaField.setEchoChar((char) 0);
        } else {
            confirmarContrasenaField.setEchoChar('*');
        }
    }//GEN-LAST:event_checkboxConfirmarMostrarContrasenaActionPerformed

    private void checkboxMostrarContrasenaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_checkboxMostrarContrasenaActionPerformed
        if (checkboxMostrarContrasena.isSelected()) {
            contrasenaField.setEchoChar((char) 0);
        } else {
            contrasenaField.setEchoChar('*');
        }
    }//GEN-LAST:event_checkboxMostrarContrasenaActionPerformed

    private void confirmarContrasenaFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_confirmarContrasenaFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_confirmarContrasenaFieldActionPerformed

    /**
     * Cierra la ventana de agregar usuario.
     * @param evt
     */
    private void botonCancelarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonCancelarActionPerformed
        dispose();
    }//GEN-LAST:event_botonCancelarActionPerformed
    private UsuarioDTO.Puesto getPuestoFromComboBox(String puestoString) {
        switch (puestoString) {
            case "GERENTE":
                return UsuarioDTO.Puesto.GERENTE;
            case "CAJERO":
                return UsuarioDTO.Puesto.CAJERO;
            default:
                throw new IllegalArgumentException("Puesto desconocido: " + puestoString);
        }
    }

    /**
     * Restablece los campos de la ventana de agregar usuario.
     * @param evt
     */
    private void botonRestablecerActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonRestablecerActionPerformed
        fieldNombreUsuario.setText("");
        fieldApellidoUsuario.setText("");
        fieldTelefono.setText("");
        fieldCalle.setText("");
        fieldColonia.setText("");
        fieldCodigoPostal.setText("");
        fieldCiudad.setText("");
        fieldNumeroEdificio.setText("");
        contrasenaField.setText("");
        confirmarContrasenaField.setText("");
    }//GEN-LAST:event_botonRestablecerActionPerformed

    /**
     * Agrega un usuario a la base de datos.
     * @param evt
     */
    private void botonAgregarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonAgregarActionPerformed
        // Obtener los valores de los campos
        String nombreUsuario = fieldNombreUsuario.getText().trim();
        String apellidoUsuario = fieldApellidoUsuario.getText().trim();
        String telefono = fieldTelefono.getText().trim();
        String calle = fieldCalle.getText().trim();
        String colonia = fieldColonia.getText().trim();
        String codigoPostal = fieldCodigoPostal.getText().trim();
        String ciudad = fieldCiudad.getText().trim();
        String numeroEdificio = fieldNumeroEdificio.getText().trim();
        String contrasena = new String(contrasenaField.getPassword());
        String confirmarContrasena = new String(confirmarContrasenaField.getPassword());
        String codigoInterno = fieldCodigoInterno.getText().trim();

        // Validar que ningún campo esté vacío
        if (nombreUsuario.isEmpty() || apellidoUsuario.isEmpty() || telefono.isEmpty() || calle.isEmpty()
                || colonia.isEmpty() || codigoPostal.isEmpty() || ciudad.isEmpty() || numeroEdificio.isEmpty()
                || contrasena.isEmpty() || confirmarContrasena.isEmpty()) {
            JOptionPane.showMessageDialog(agregarUsuarioFrame.this, "Todos los campos deben estar llenos.", "Error", JOptionPane.ERROR_MESSAGE);
            return;
        }

        // Validar nombre de usuario
        if (!nombreUsuario.matches("^[a-zA-Z]+$")) {
            JOptionPane.showMessageDialog(agregarUsuarioFrame.this, "Nombre de Usuario solo puede contener letras.", "Error", JOptionPane.ERROR_MESSAGE);
            return;
        }

        // Validar apellido de usuario
        if (!apellidoUsuario.matches("^[a-zA-Z]+$")) {
            JOptionPane.showMessageDialog(agregarUsuarioFrame.this, "Apellido de Usuario solo puede contener letras.", "Error", JOptionPane.ERROR_MESSAGE);
            return;
        }

        // Validar teléfono
        if (!telefono.matches("^\\d{10}$")) {
            JOptionPane.showMessageDialog(agregarUsuarioFrame.this, "Teléfono debe contener solo 10 números.", "Error", JOptionPane.ERROR_MESSAGE);
            return;
        }

        // Validar calle
        if (!calle.matches("^[a-zA-Z]+$")) {
            JOptionPane.showMessageDialog(agregarUsuarioFrame.this, "Calle solo puede contener letras.", "Error", JOptionPane.ERROR_MESSAGE);
            return;
        }

        // Validar colonia
        if (!colonia.matches("^[a-zA-Z]+$")) {
            JOptionPane.showMessageDialog(agregarUsuarioFrame.this, "Colonia solo puede contener letras.", "Error", JOptionPane.ERROR_MESSAGE);
            return;
        }

        // Validar código postal
        if (!codigoPostal.matches("^\\d{5}$")) {
            JOptionPane.showMessageDialog(agregarUsuarioFrame.this, "Código Postal debe contener solo 5 números.", "Error", JOptionPane.ERROR_MESSAGE);
            return;
        }

        // Validar ciudad
        if (!ciudad.matches("^[a-zA-Z]+$")) {
            JOptionPane.showMessageDialog(agregarUsuarioFrame.this, "Ciudad solo puede contener letras.", "Error", JOptionPane.ERROR_MESSAGE);
            return;
        }

        // Validar número de edificio
        if (!numeroEdificio.matches("^\\d+$")) {
            JOptionPane.showMessageDialog(agregarUsuarioFrame.this, "Número de Edificio solo puede contener números.", "Error", JOptionPane.ERROR_MESSAGE);
            return;
        }

        // Validar contraseña
        if (contrasena.length() < 6) {
            JOptionPane.showMessageDialog(agregarUsuarioFrame.this, "Contraseña debe tener al menos 6 caracteres.", "Error", JOptionPane.ERROR_MESSAGE);
            return;
        }

        // Validar confirmar contraseña
        if (!contrasena.equals(confirmarContrasena)) {
            JOptionPane.showMessageDialog(agregarUsuarioFrame.this, "Confirmar Contraseña debe ser igual a la Contraseña.", "Error", JOptionPane.ERROR_MESSAGE);
            return;
        }

        // Validar código interno
        if (!codigoInterno.matches("^[A-Z]{3}\\d{3}$")) {
            JOptionPane.showMessageDialog(agregarUsuarioFrame.this,
                    "Código Interno debe tener el formato de 3 letras y luego 3 números (ejemplo: SAB001).", "Error",
                    JOptionPane.ERROR_MESSAGE);
            return;
        }
        GestorUsuarios gu;
        try {
            gu = new GestorUsuarios();
            UsuarioDTO usuario = new UsuarioDTO();
            usuario.setCodigoInterno(codigoInterno);
            usuario.setNombre(nombreUsuario);
            usuario.setApellido(apellidoUsuario);
            usuario.setFechaContratacion(new Date());
            String puestoString = (String) cajeroComboBox.getSelectedItem();
            usuario.setPuesto(getPuestoFromComboBox(puestoString));
            usuario.setTelefono(telefono);
            usuario.setContrasena(contrasena);
            DireccionDTO direccion = new DireccionDTO();
            direccion.setCalle(calle);
            direccion.setColonia(colonia);
            direccion.setCodigoPostal(codigoPostal);
            direccion.setCiudad(ciudad);
            direccion.setNumeroEdificio(numeroEdificio);
            usuario.setDireccion(direccion);
            try {
                gu.insertar(usuario);
                JOptionPane.showMessageDialog(agregarUsuarioFrame.this, "Usuario agregado correctamente.", "Éxito", JOptionPane.INFORMATION_MESSAGE);
            } catch (PersistenciaException e) {
                JOptionPane.showMessageDialog(agregarUsuarioFrame.this, "Error al agregar usuario.", "Error", JOptionPane.ERROR_MESSAGE);
            }
        } catch (PersistenciaException ex) {
            Logger.getLogger(agregarUsuarioFrame.class.getName()).log(Level.SEVERE, null, ex);
        }

        dispose();
        logFrame log = new logFrame();
        log.setVisible(true);
    }//GEN-LAST:event_botonAgregarActionPerformed

    private void fieldNombreUsuarioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_fieldNombreUsuarioActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_fieldNombreUsuarioActionPerformed

    /**
     * Método main de la clase agregarUsuarioFrame.
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(agregarUsuarioFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(agregarUsuarioFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(agregarUsuarioFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(agregarUsuarioFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new agregarUsuarioFrame().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton botonAgregar;
    private javax.swing.JButton botonCancelar;
    private javax.swing.JButton botonRestablecer;
    private javax.swing.JComboBox<String> cajeroComboBox;
    private javax.swing.JCheckBox checkboxConfirmarMostrarContrasena;
    private javax.swing.JCheckBox checkboxMostrarContrasena;
    private javax.swing.JPasswordField confirmarContrasenaField;
    private javax.swing.JPasswordField contrasenaField;
    private javax.swing.JTextField fieldApellidoUsuario;
    private javax.swing.JTextField fieldCalle;
    private javax.swing.JTextField fieldCiudad;
    private javax.swing.JTextField fieldCodigoInterno;
    private javax.swing.JTextField fieldCodigoPostal;
    private javax.swing.JTextField fieldColonia;
    private javax.swing.JTextField fieldNombreUsuario;
    private javax.swing.JTextField fieldNumeroEdificio;
    private javax.swing.JTextField fieldTelefono;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    // End of variables declaration//GEN-END:variables
}
